version: '3.4'

services:
  codechallenge:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cashdb:6379"
    ports:
     - "5150:80"

    depends_on:
       - "CodeChallengemongo"
       - "cashdb"
       - "elasticsearch"

    networks:
      - elastic 
  CodeChallengemongo:
    container_name: CodeChallengemongo
    image: mongo
    restart: always
    volumes:
      #- ${WEBAPP_STORAGE_HOME}/site:/data/db
      - ../../CodeChallengDB:/data/db
    ports:
      - "27017:27017"
    networks:
      - elastic
  cashdb:
    container_name: cashdb
    restart: always    
    ports:
        - "6379:6379"
    networks:
      - elastic
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.2.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic      

volumes:
  es_data:
    driver: local

networks:
  elastic:

      
